[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
api = { path = "../api" }
err = { version = "0.0.5", package = "rmw_err" }
speedy = { path = "../lib/speedy" }
tungstenite = "0.17.3"
anyhow = "1.0.58"
rmw_log = "0.0.8"
